from __future__ import annotations


def help_text() -> str:
    return (
        "kplog 指令总览（QQ 专用）\n"
        "\n"
        "帮助：\n"
        "- /kplog help\n"
        "\n"
        "规划：\n"
        "- /kplog plan add <name> [--alias <alias>] [--note <text>]\n"
        "- /kplog plan ls [--active]\n"
        "- /kplog plan show <P#|alias>\n"
        "- /kplog plan rename <P#|alias> <new_name>\n"
        "- /kplog plan alias <P#|alias> <alias>\n"
        "- /kplog plan archive <P#|alias>\n"
        "\n"
        "阶段：\n"
        "- /kplog stage add <P#|alias> <name> --start <dt> --end <dt> [--note <text>]\n"
        "- /kplog stage ls <P#|alias>\n"
        "- /kplog stage show <S#>\n"
        "- /kplog stage time <S#> --start <dt> --end <dt>\n"
        "- /kplog stage rename <S#> <new_name>\n"
        "\n"
        "任务：\n"
        "- /kplog task add <S#> <name> [--order <n>] [--note <text>]\n"
        "- /kplog task ls <S#> [--all]\n"
        "- /kplog task show <T#>\n"
        "- /kplog task order <T#> <n>\n"
        "- /kplog task rename <T#> <new_name>\n"
        "- /kplog task prog <T#> <0-100> [--note <text>]\n"
        "- /kplog task state <T#> <todo|doing|done> [--note <text>]\n"
        "\n"
        "计时：\n"
        "- /kplog timer start <T#> [--remind <minutes|off>] [--to <session>]\n"
        "- /kplog timer stop [--note <text>]\n"
        "- /kplog timer status\n"
        "- /kplog timer remind <minutes|off>\n"
        "\n"
        "快捷推进：\n"
        "- /kplog prog <0-100> [--note <text>]\n"
        "\n"
        "日志：\n"
        "- /kplog log add <text> [--task <T#>] [--min <n>] [--prog <0-100>]\n"
        "- /kplog log ls <T#> [--date <YYYY-MM-DD>]\n"
        "\n"
        "日报：\n"
        "- /kplog daily open <YYYY-MM-DD> [--plan <P#|alias>]\n"
        "- /kplog daily add done|block|next|note <text>\n"
        "- /kplog daily show <YYYY-MM-DD> [--plan <P#|alias>]\n"
        "- /kplog daily gen <YYYY-MM-DD> [--plan <P#|alias>]\n"
    )
