from __future__ import annotations


def help_text() -> str:
    return (
        "klog 指令总览（QQ 专用）\n"
        "\n"
        "帮助：\n"
        "- /klog help\n"
        "\n"
        "规划：\n"
        "- /klog plan add <name> [--alias <alias>] [--note <text>]\n"
        "- /klog plan ls [--active]\n"
        "- /klog plan show <P#|alias>\n"
        "- /klog plan rename <P#|alias> <new_name>\n"
        "- /klog plan alias <P#|alias> <alias>\n"
        "- /klog plan archive <P#|alias>\n"
        "\n"
        "阶段：\n"
        "- /klog stage add <P#|alias> <name> --start <dt> --end <dt> [--note <text>]\n"
        "- /klog stage ls <P#|alias>\n"
        "- /klog stage show <S#>\n"
        "- /klog stage time <S#> --start <dt> --end <dt>\n"
        "- /klog stage rename <S#> <new_name>\n"
        "\n"
        "任务：\n"
        "- /klog task add <S#> <name> [--order <n>] [--note <text>]\n"
        "- /klog task ls <S#> [--all]\n"
        "- /klog task show <T#>\n"
        "- /klog task order <T#> <n>\n"
        "- /klog task rename <T#> <new_name>\n"
        "- /klog task prog <T#> <0-100> [--note <text>]\n"
        "- /klog task state <T#> <todo|doing|done> [--note <text>]\n"
        "\n"
        "计时：\n"
        "- /klog timer start <T#> [--remind <minutes|off>] [--to <session>]\n"
        "- /klog timer stop [--note <text>]\n"
        "- /klog timer status\n"
        "- /klog timer remind <minutes|off>\n"
        "\n"
        "快捷推进：\n"
        "- /klog prog <0-100> [--note <text>]\n"
        "\n"
        "日志：\n"
        "- /klog log add <text> [--task <T#>] [--min <n>] [--prog <0-100>]\n"
        "- /klog log ls <T#> [--date <YYYY-MM-DD>]\n"
        "\n"
        "日报：\n"
        "- /klog daily open <YYYY-MM-DD> [--plan <P#|alias>]\n"
        "- /klog daily add done|block|next|note <text>\n"
        "- /klog daily show <YYYY-MM-DD> [--plan <P#|alias>]\n"
        "- /klog daily gen <YYYY-MM-DD> [--plan <P#|alias>]\n"
    )
